[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/comanda/:id/item/:index"
  to = "/.netlify/functions/comanda-item/:id/:index"
  status = 200

[[redirects]]
  from = "/api/comanda/:id"
  to = "/.netlify/functions/comanda/:id"
  status = 200
